# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: aleon-ca <aleon-ca@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/01/18 17:33:29 by aleon-ca          #+#    #+#              #
#    Updated: 2021/01/18 17:33:34 by aleon-ca         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SRCS = ./*.c

OBJS = $(SRCS:.c=.o)

NAME = philo_one

INCLUDE = -lpthread
FLAGS = -Werror -Wextra -Wall
GCC = gcc $(FLAGS) -I. $(INCLUDE)

RM = rm -f

all:		$(NAME)

$(NAME):	$(OBJS)
	$(GCC) $(OBJS) -o $(NAME)

clean:
	$(RM) $(OBJS)

fclean:		clean
	$(RM) $(NAME)

re:		fclean all

.PHONY:		all clean fclean re
